version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: postgres12_postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=psql&4n4l1s1s
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
